### ISSUE TITLE
[Design] Les (i) ne s'affichent pas chez moi

### ISSUE THREAD

**Issue by gillesvallier** [Carbon-Target/carbon_target#100]
![image](https://user-images.githubusercontent.com/96253477/179191508-5fe16916-77ce-490d-892a-3db28ded1000.png)

Je navigue sur Chrome.

**Comment by meuble** [comment]
C'était du à la manip pour te mettre à disposition les deux environnements. Maintenant que le code est mergé, c'est corrigé.
