### ISSUE TITLE
Changer l'adresse mail

### ISSUE THREAD

**Issue by gillesvallier** [Carbon-Target/carbon_target#120]
Dans la pop-up "A propos", changer l'adresse mail "hello@carbontarget.earth" par "gilles.vallier.perso@gmail.com" (les adresses mails Gandi deviennent payantes...)

**Comment by meuble** [comment]
Est ce que ce n'est pas mieux de garder hello@carbontarget.earth d'afficher, et d'utiliser une redirection vers ton adresse personnelle ? (c'est gratuit)

**Comment by stephaneakkaoui-tagheuer** [comment]
Oui, elle n'existera plus, mais on devrait continuer de pouvoir faire des redirections.

**Comment by gillesvallier** [comment]
Trop bien alors !
