### ISSUE TITLE
Introduction des curseurs plafonnés

### ISSUE THREAD

**Issue by gillesvallier** [Carbon-Target/carbon_target#34]
Plusieurs points clés : 
 - l'objectif global devient contraignant et ne peut être dépassé (pour marquer une différence réelle technique avec les calculateurs d'empreinte carbone, le but étant de clarifier l'objectif de l'outil par l'usage)
 - par conséquent, l'objectif devient modifiable (par tranche de 1 tonne)
 - les champs de saisie par item sont remplacés par des curseurs modifiables
 - les sous-totaux par catégorie sont également remplacés par des curseurs modifiables
 - les curseurs ont tous un minimum à 0 (à l'exception du curseur "Se nourrir") et un maximum qui est la transcription de l'objectif global pour les sous-totaux, et la transcription du sous-total pour les items (à l'exception des curseurs des items "Se nourrir" qui sont limités par définition à 21 repas par semaine)
 - pour simplifier l'ergonomie, on vire les "select", on impose un choix pertinent spécifique à chaque item
 - l'utilisateur ajuste en premier lieu les sous-totaux par catégorie, et ensuite les items à l'intérieur d'une catégorie
 - lorsque l'utilisateur augmente un curseur, si cela a pour conséquence de dépasser l'objectif global (pour les sous-totaux) ou le sous-total (pour les items), les autres curseurs sont automatiquement impactés à la baisse pour rester au niveau de l'objectif global (répartition de la baisse à parts égales entre les curseurs concernés)
 - pour rendre l'outil manipulable, possibilité de "verrouiller" (ou de "déverrouiller") un curseur en 1 clic --> lorsqu'un curseur est verrouillé, il n'est plus impacté par les ajustements automatiques

Questions : 
 - les curseurs sont-ils horizontaux ou verticaux ?
 - comment modifier l'objectif principal de manière simple et jolie ? (bouton +/- ? ...)
 - un scénario de base est-il prérempli au départ ?
 - est-ce que l'ajustement à la baisse est réalisé automatiquement ou est-il simplement suggéré par un code couleur (ou un marqueur) sur les curseurs concernés ?

**Comment by meuble** [comment]
[scc-la-vache-noire_contacts_17-02-2022.csv](https://github.com/Carbon-Target/carbon_target/files/8096245/scc-la-vache-noire_contacts_17-02-2022.csv)

**Comment by meuble** [comment]
![IMG_1674](https://user-images.githubusercontent.com/24662/154664682-b51383cc-9439-4109-b95e-a19a1ae25c36.jpg)
