### ISSUE TITLE
Algorithme valeur de curseur et max par item

### ISSUE THREAD

**Issue by GabGab** [Carbon-Target/carbon_target#37]
TEDLT

**Comment by gillesvallier** [comment]
Règle de calcul des valeurs de curseur :

Principes généraux catégories
 - Lorsque le budget d'une catégorie évolue de y% (où y% désigne la variation absolue de la valeur en %), la valeur des autres catégories (modifiables) est ajustée de "-y% / nb de catégories modifiables" (ce cas ne se déclenche donc pas lorsqu'on modifie le budget global puisqu'il n'y a pas de variations des % par catégories)
 - Les valeurs de catégorie en % sont affichées avec 1 chiffre après la virgule arrondi à la décimale la plus proche, mais l'utilisateur ne peut "toucher" que des entiers lorsqu'il manipule le curseur
 - Si lors d'un ajustement, une catégorie arrive en butée (min ou max), le solde d'ajustement résiduel (en %) est répercuté sur les autres catégories selon la même règle de calcul (seul le nb de catégories modifiables change)
 - Lorsque l'ajustement n'est plus possible, le résidu d'ajustement n'est pas effectué et est annulé (dit autrement le curseur que l'utilisateur tente de modifier ne bouge plus)

Principes généraux items
 - Lorsque le budget d'une catégorie évolue de x% (où x% désigne la variation relative de la valeur en kg), la valeur de chaque item (non verrouillé) de la catégorie est ajustée de x%, arrondie à l'entier la plus proche (c'est ce cas qui se déclenche lorsqu'on modifie le budget global)
 - Lorsque une valeur d'item est modifiée de x kg, la valeur des autres items (modifiables) de la catégorie est ajustée de "-x kg * kg C02 de l'item avant modif / somme des kg CO2 avant modif des items modifiables de la catégorie", arrondie à l'entier le plus proche
 - Si lors d'un ajustement, un item arrive en butée (min ou max), le solde d'ajustement résiduel (en kg) est répercuté sur les autres items selon la même règle de calcul (seul le nombre d'items modifiables change)
 - Lorsque l'ajustement n'est plus possible, le résidu d'ajustement n'est pas effectué et est annulé (dit autrement le curseur que l'utilisateur tente de modifier ne bouge plus)
 - Les valeurs de chaque curseur d'item sont forcément des nombres entiers

Principes spécifiques - Repas
 - Total des 3 curseurs = 21 repas
 - + 1 repas boeuf --> prio 1 : - 1 repas végé / prio 2 : - 1 repas poulet
 - + 1 repas poulet --> prio 1 : - 1 repas végé / prio 2 : - 1 repas boeuf
 - + 1 repas végé --> prio 1 : - 1 repas boeuf / prio 2 : - 1 repas poulet

Principe spécifique - Logement
 - Le curseur de l'item logement n'est pas modifiable (puisque c'est le seul item), il faut modifier la catégorie

**Comment by gillesvallier** [comment]
Voici les règles pour définir le min et max des curseurs par catégorie :

Repas

Min = 557 kg --> "Min Repas" à chiffrer en % en fonction de l'objectif global
Max = 100 %

Transport

Min = 0 %
Max = 100% - Min repas

S'équiper

Min = 0 %
Max = 100% - Min Repas

Se loger

Min : 0%
Max = 100% - Min Repas
