### ISSUE TITLE
Ajouter une note de type "DPE" sur le logement

### ISSUE THREAD

**Issue by gillesvallier** [Carbon-Target/carbon_target#41]
Pour différencier les types de logement, on pourrait ajouter la possibilité de sélectionner la catégorie "DPE" du logement (de A à G), avec une petite échelle de ce style (au format horizontal et en gardant uniquement les étiquettes de lettres) : 
![image](https://user-images.githubusercontent.com/96253477/154708200-225873ee-a3ad-4fa5-9e5b-cd9514894e4f.png)

Le coefficient varierait ainsi en fonction de la lettre sélectionnée : 
 - A = 3 kgCO2/m²/an
 - B = 8,5 kgCO2/m²/an
 - C = 20,5 kgCO2/m²/an
 - D = 40 kgCO2/m²/an
 - E = 60 kgCO2/m²/an
 - F = 85 kgCO2/m²/an
 - G = 120 kgCO2/m²/an

DPE = Diagnostic de Performance Energétique

**Comment by gillesvallier** [comment]
Ce concept peut d'ailleurs être utilisé pour réduire le nombre d'items de "Se déplacer", avec un choix "Type de voiture", et un choix "Type de vol en avion".

**Comment by gillesvallier** [comment]
Mettre en valeur par défaut "B" et 48m² pour le logement

**Comment by meuble** [comment]
Fixed by #47
