### ISSUE TITLE
[Bug] Fonction "ajouter un moyen de transport"

### ISSUE THREAD

**Issue by gillesvallier** [Carbon-Target/carbon_target#64]
1. Lorsqu'on ajoute un moyen de transport, le texte des "select" (pour les 3 : voiture, train et avion) ne sort pas correctement.

2. Par ailleurs, le max du select qui est ajouté ne correspond pas à la formule : MAX = Budget global / FE

**Comment by meuble** [comment]
T'as un screenshot pour expliciter le "ne sort pas correctement.", stp ?

**Comment by gillesvallier** [comment]
Exemple pour l'avion : 
![image](https://user-images.githubusercontent.com/96253477/171055014-64d79321-f060-49ec-9b4a-1a306c80673e.png)

**Comment by gillesvallier** [comment]
Voiture : 
![image](https://user-images.githubusercontent.com/96253477/171055066-75b072c8-7f7d-441f-9266-1b327b2b89ea.png)

Train : 
![image](https://user-images.githubusercontent.com/96253477/171055131-b6fd2089-2a76-402f-8291-ba4d37d1608e.png)
